name: Delete Stale Cloudinary Images

on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Call function
      run: curl https://matte.pics/api/clean-uploads
